# Generated by Django 2.2.6 on 2020-12-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        ('aspects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('CM', 'Completed'), ('CR', 'Created'), ('DR', 'Draft'), ('EV', 'Evaluation'), ('IP', 'In Progress'), ('PD', 'Paid'), ('RJ', 'Rejected'), ('SM', 'Submitted')], default='CR', max_length=2)),
                ('total_lamp', models.IntegerField(default=0)),
                ('total_led', models.IntegerField(default=0)),
                ('vehicle_car', models.IntegerField(default=0)),
                ('vehicle_motorcycle', models.IntegerField(default=0)),
                ('vehicle_bicycle', models.IntegerField(default=0)),
                ('vehicle_other', models.IntegerField(default=0)),
                ('electricity_bill_1_month', models.DateField(null=True)),
                ('electricity_bill_1_usage', models.IntegerField(default=0)),
                ('electricity_bill_2_month', models.DateField(null=True)),
                ('electricity_bill_2_usage', models.IntegerField(default=0)),
                ('electricity_bill_3_month', models.DateField(null=True)),
                ('electricity_bill_3_usage', models.IntegerField(default=0)),
                ('water_bill_1_month', models.DateField(null=True)),
                ('water_bill_1_usage', models.IntegerField(default=0)),
                ('water_bill_2_month', models.DateField(null=True)),
                ('water_bill_2_usage', models.IntegerField(default=0)),
                ('water_bill_3_month', models.DateField(null=True)),
                ('water_bill_3_usage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAssessment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_assessment_application', to='applications.Application')),
                ('assessment_aspect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_assessment_assessment_aspect', to='aspects.Aspect')),
                ('supporting_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_supporting_doc', to='medias.Media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvaluationSchedule',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_schedule_application', to='applications.Application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvaluation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('equipment', models.IntegerField(default=0)),
                ('system', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_application_assessment', to='applications.ApplicationAssessment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
