# Generated by Django 2.2.6 on 2020-06-23 08:34

from django.db import migrations, models
import django.db.models.deletion
import ghg.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aspects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('CM', 'Completed'), ('CR', 'Created'), ('DR', 'Draft'), ('EV', 'Evaluation'), ('IP', 'In Progress'), ('PD', 'Paid'), ('RJ', 'Rejected'), ('SM', 'Submitted')], default='CR', max_length=2)),
                ('total_lamp', models.IntegerField(blank=True, default=0)),
                ('total_led', models.IntegerField(blank=True, default=0)),
                ('vehicle_car', models.IntegerField(blank=True, default=0)),
                ('vehicle_motorcycle', models.IntegerField(blank=True, default=0)),
                ('vehicle_bicycle', models.IntegerField(blank=True, default=0)),
                ('vehicle_other', models.IntegerField(blank=True, default=0)),
                ('electricity_bill_1_month', models.CharField(default='NA', max_length=100)),
                ('electricity_bill_1_usage', models.IntegerField(default=0)),
                ('electricity_bill_1_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('bills'))),
                ('electricity_bill_2_month', models.CharField(default='NA', max_length=100)),
                ('electricity_bill_2_usage', models.IntegerField(default=0)),
                ('electricity_bill_2_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('bills'))),
                ('electricity_bill_3_month', models.CharField(default='NA', max_length=100)),
                ('electricity_bill_3_usage', models.IntegerField(default=0)),
                ('electricity_bill_3_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('bills'))),
                ('water_bill_1_month', models.CharField(default='NA', max_length=100)),
                ('water_bill_1_usage', models.IntegerField(default=0)),
                ('water_bill_1_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('bills'))),
                ('water_bill_2_month', models.CharField(default='NA', max_length=100)),
                ('water_bill_2_usage', models.IntegerField(default=0)),
                ('water_bill_2_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('bills'))),
                ('water_bill_3_month', models.CharField(default='NA', max_length=100)),
                ('water_bill_3_usage', models.IntegerField(default=0)),
                ('water_bill_3_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('bills'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remarks', models.CharField(blank=True, default='NA', max_length=255)),
                ('supporting_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('assessment'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_assessment_application', to='applications.Application')),
                ('assessment_aspect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_assessment_assessment_aspect', to='aspects.Aspect')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvaluationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_schedule_application', to='applications.Application')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment', models.IntegerField(default=0)),
                ('system', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('remarks', models.CharField(default='NA', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('application_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_application_assessment', to='applications.ApplicationAssessment')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
