# Generated by Django 2.2.6 on 2020-12-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
        ('medias', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(limit_choices_to={'user_type': 'AP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='applied_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_applied_house', to='houses.House'),
        ),
        migrations.AddField(
            model_name='application',
            name='electricity_bill_1_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_electricity_bill_1', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='application',
            name='electricity_bill_2_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_electricity_bill_2', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='application',
            name='electricity_bill_3_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_electricity_bill_3', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='application',
            name='evaluator_nominated',
            field=models.ForeignKey(limit_choices_to={'user_type': 'EV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_evaluator_nominated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='water_bill_1_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_water_bill_1', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='application',
            name='water_bill_2_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_water_bill_2', to='medias.Media'),
        ),
        migrations.AddField(
            model_name='application',
            name='water_bill_3_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_water_bill_3', to='medias.Media'),
        ),
    ]
