# Generated by Django 2.2.6 on 2020-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200623_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='applicationassessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='applicationevaluation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='applicationevaluationschedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='applicationassessment',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='applicationassessment',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='applicationevaluation',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='applicationevaluation',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='applicationevaluationschedule',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='applicationevaluationschedule',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='electricity_bill_1_month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='electricity_bill_2_month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='electricity_bill_3_month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='water_bill_1_month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='water_bill_2_month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='water_bill_3_month',
            field=models.DateField(null=True),
        ),
    ]
