# Generated by Django 2.2.6 on 2020-07-14 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200707_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(limit_choices_to={'user_type': 'AP'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='electricity_bill_1_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='electricity_bill_2_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='electricity_bill_3_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='evaluator_nominated',
            field=models.ForeignKey(limit_choices_to={'user_type': 'EV'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_evaluator_nominated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='water_bill_1_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='water_bill_2_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='water_bill_3_usage',
            field=models.FloatField(default=0),
        ),
    ]
