apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: mbpj-ghg-webapp
  name: mbpj-ghg-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: mbpj-ghg-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mbpj-ghg-webapp
    spec:
      containers:
      - image: afizihusaini/mbpj-ghg-webapp:1.1.2
        imagePullPolicy: Always   
        name: mbpj-ghg-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30