# Generated by Django 2.2.6 on 2020-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20200212_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationassessment',
            name='total_lamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='total_led',
            field=models.IntegerField(default=0),
        ),
    ]
