# Generated by Django 2.2.6 on 2020-05-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20200226_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationassessment',
            name='remarks',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationassessment',
            name='total_lamp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='applicationassessment',
            name='total_led',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
