# Generated by Django 2.2.6 on 2021-04-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20200508_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationassessment',
            name='total_lamp',
        ),
        migrations.RemoveField(
            model_name='applicationassessment',
            name='total_led',
        ),
    ]
