# Generated by Django 2.2.6 on 2021-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20210426_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationassessment',
            name='total_lamp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='total_led',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
