# Generated by Django 2.2.6 on 2021-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20210505_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationassessment',
            name='total_lamp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applicationassessment',
            name='total_led',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
