# Generated by Django 2.2.6 on 2021-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20210506_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_approved',
            field=models.DateField(null=True),
        ),
    ]
