# Generated by Django 2.2.6 on 2021-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_application_date_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='remarks',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
    ]
