apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbpj-ghg-api-celery-beat
  labels:
    deployment: mbpj-ghg-api-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mbpj-ghg-api-celery-beat
  template:
    metadata:
      labels:
        pod: mbpj-ghg-api-celery-beat
    spec:
      containers:
        - name: mbpj-ghg-api-celery-beat
          image: syafiqpipe/mbpj-ghg-api
          # celery -A mbpj-ghgapi beat -l debug
          command: ['celery', '-A', 'ghg', 'beat', '-l', 'debug']
          envFrom:
            - secretRef:
                name: mbpj-ghg-api-secret   