# Generated by Django 2.2.6 on 2021-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0004_auto_20200212_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebate',
            name='amount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rebate',
            name='amount_approved',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
