# Generated by Django 2.2.6 on 2021-07-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0005_auto_20210722_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebate',
            name='amount_percent',
        ),
    ]
