# Generated by Django 2.2.6 on 2020-02-26 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroccupation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
