# Generated by Django 2.2.6 on 2020-02-26 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useroccupation_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined']},
        ),
    ]
