# Generated by Django 2.2.6 on 2020-12-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebate',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount_approved', models.IntegerField(default=0)),
                ('remarks', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.Application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
