# Generated by Django 2.2.6 on 2020-07-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rebate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='rebate',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rebate',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
