# Generated by Django 2.2.6 on 2020-07-14 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0002_auto_20200707_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebate',
            name='amount_approved',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rebate',
            name='application',
            field=models.ForeignKey(limit_choices_to={'status': 'AP'}, on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
    ]
