# Generated by Django 2.2.6 on 2020-10-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0003_auto_20200714_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebate',
            name='amount_approved',
            field=models.IntegerField(default=0),
        ),
    ]
