# Generated by Django 2.2.6 on 2020-12-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, null=True)),
                ('address_1', models.CharField(max_length=100, null=True)),
                ('address_2', models.CharField(max_length=100, null=True)),
                ('address_3', models.CharField(max_length=100, null=True)),
                ('postcode', models.CharField(max_length=5, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(default='SELANGOR', max_length=100)),
                ('building_type', models.CharField(choices=[('CD', 'Condominium'), ('FL', 'Flat'), ('TO', 'Townhouse'), ('TE', 'Terrace House'), ('BS', 'Bungalow / Semidetached'), ('AS', 'Apartment / Service Apartment'), ('OT', 'Other')], default='BG', max_length=2)),
                ('assessment_tax_account', models.CharField(max_length=100, null=True)),
                ('staying_since', models.DateField(null=True)),
                ('occupants', models.IntegerField(default=1)),
                ('relationship_type', models.CharField(choices=[('SL', 'Self'), ('SP', 'Spouse'), ('SB', 'Siblings'), ('PR', 'Parents'), ('CH', 'Children'), ('OT', 'Others')], default='SL', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assessment_tax_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_assessment_tax_doc', to='medias.Media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
