# Generated by Django 2.2.6 on 2020-06-23 08:34

from django.db import migrations, models
import ghg.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=5)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('building_type', models.CharField(choices=[('CD', 'Condominium'), ('FL', 'Flat'), ('TO', 'Townhouse'), ('TE', 'Terrace House'), ('BS', 'Bungalow / Semidetached'), ('AS', 'Apartment / Service Apartment'), ('OT', 'Other')], default='BG', max_length=2)),
                ('assessment_tax_account', models.CharField(blank=True, max_length=100)),
                ('assessment_tax_doc', models.ImageField(null=True, upload_to=ghg.helpers.PathAndRename('assessment_tax'))),
                ('staying_duration_since', models.CharField(blank=True, max_length=5)),
                ('occupants', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
