# Generated by Django 2.2.6 on 2020-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='staying_duration_since',
        ),
        migrations.AddField(
            model_name='house',
            name='staying_since',
            field=models.DateField(null=True),
        ),
    ]
