# Generated by Django 2.2.6 on 2020-07-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20200707_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='relationship_type',
            field=models.CharField(choices=[('SL', 'Self'), ('SP', 'Spouse'), ('SB', 'Siblings'), ('PR', 'Parents'), ('CH', 'Children'), ('OT', 'Others')], default='SL', max_length=2),
        ),
    ]
