# Generated by Django 2.2.6 on 2020-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200212_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanswer',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
