# Generated by Django 2.2.6 on 2020-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200522_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketanswer',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
