# Generated by Django 2.2.6 on 2020-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketanswer_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketanswer',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='ticketquestion',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketquestion',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
