# Generated by Django 2.2.6 on 2020-06-23 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('aspect_type', models.CharField(choices=[('EN', 'Energy'), ('WA', 'Water'), ('TR', 'Transportation'), ('BI', 'Biodiversity'), ('WE', 'Waste'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('incentive', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
