# Generated by Django 2.2.6 on 2020-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('aspect_type', models.CharField(choices=[('EN', 'Energy'), ('WA', 'Water'), ('TR', 'Transportation'), ('BI', 'Biodiversity'), ('WE', 'Waste'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('description_en', models.CharField(max_length=100, null=True)),
                ('description_ms', models.CharField(max_length=100, null=True)),
                ('incentive', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
