# Generated by Django 2.2.6 on 2020-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspect',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='aspect',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='aspect',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='aspect',
            name='description_ms',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
