# Generated by Django 2.2.6 on 2020-07-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0002_auto_20200707_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspect',
            name='incentive',
            field=models.FloatField(default=0),
        ),
    ]
